newyml

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -1,42 +1,32 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-# This workflow will install Deno then run `deno lint` and `deno test`.
-# For more information see: https://github.com/denoland/setup-deno
-
-name: Deno
+name: Test Node.js script
 
 on:
   push:
-    branches: ["main"]
+    branches:
+      - tariqajies-svg-patch-1
   pull_request:
-    branches: ["main"]
-
-permissions:
-  contents: read
+    branches:
+      - tariqajies-svg-patch-1
 
 jobs:
   test:
-    runs-on: ubuntu-latest
+    runs-on: instanceelk
 
     steps:
-      - name: Setup repo
-        uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - name: Setup Deno
-        # uses: denoland/setup-deno@v1
-        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
+      - name: Install Node.js
+        uses: actions/setup-node@v2
         with:
-          deno-version: v1.x
+          node-version: 14
 
-      # Uncomment this step to verify the use of 'deno fmt' on each commit.
-      # - name: Verify formatting
-      #   run: deno fmt --check
-
-      - name: Run linter
-        run: deno lint
-
-      - name: Run tests
-        run: deno test -A
+      - name: Run Node.js script
+        run: |
+          output=$(node main.js)
+          if echo "$output" | grep -q "hello"; then
+            echo "Hello found in output: $output"
+          else
+            echo "Hello not found in output: $output"
+            exit 1
+          fi
